### ISSUE TITLE
Oracle JDBC Driver - C2 Crash  [libjvm.so+0xb127c5]  PhaseIdealLoop::identical_backtoback_ifs(Node*)+0x75

### ISSUE THREAD

**Issue by zoomingrocket** [corretto/corretto-11#389]
### Describe the bug
Oracle JDBC Driver - ojdbc8.jar (19.26) JVM Crash with 

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5bace857c5, pid=624012, tid=624036
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.26.4.1 (11.0.26+4) (build 11.0.26+4-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.26.4.1 (11.0.26+4-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xb127c5]  PhaseIdealLoop::identical_backtoback_ifs(Node*)+0x75
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /d00/apps/molecule.cfs/atom/core.624012)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-11/issues/
#


---------------  S U M M A R Y ------------

Command Line: -XX:MaxMetaspaceSize=1536m -XX:G1HeapRegionSize=32m -XX:+UseCompressedClassPointers  -XX:MetaspaceSize=1536m -Xmx16384m -XX:ParallelGCThreads=8 -XX:ReservedCodeCacheSize=512m -XX:+UseCompressedOops -XX:+AlwaysPreTouch -Dsun.net.client.defaultReadTimeout=220000 -Dcom.sun.management.jmxremote.authenticate=false -XX:+UseCodeCacheFlushing -XX:+UseG1GC -XX:+DisableExplicitGC -XX:ConcGCThreads=8 -Dcom.boomi.container.securityCompatibility=2021.01 -Xms16384m -Dcom.sun.management.jmxremote.rmi.port=8686 -XX:CICompilerCount=4 -XX:MaxMetaspaceExpansion=16m -Dsun.net.client.defaultConnectTimeout=10000 -Djava.io.tmpdir=/d00/apps/node/atom/temp -XX:+HeapDumpOnOutOfMemoryError -Dsun.net.http.retryPost=false -XX:InitiatingHeapOccupancyPercent=30 -XX:G1ReservePercent=15 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:CompileThreshold=3000 -Xlog:gc*,ergo*=trace,stringdedup*=debug,age*=debug:file=/d00/apps/node/logs/jvmgc/molecule_gc_%t.log:tags,time,uptime,level:filecount=5,filesize=10M -XX:+ParallelRefProcEnabled -Dcom.boomi.container.clusterLibVersion=3 -XX:CompressedClassSpaceSize=256m -XX:MaxGCPauseMillis=1000 -Dcom.sun.management.jmxremote.port=8686 -Xss2m -XX:+UseStringDeduplication -XX:-G1UseAdaptiveIHOP -XX:MaxTenuringThreshold=1 -XX:MinMetaspaceExpansion=4m -Dcom.sun.management.jmxremote.ssl=false --add-opens=java.logging/java.util.logging=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED install4j.com.boomi.launcher.Launcher start com.boomi.container.core.Container lib work --build-number-file=bin/build.number --user-lib-dir=userlib

Host: Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz, 8 cores, 31G, Red Hat Enterprise Linux release 8.10 (Ootpa)
Time: Tue Apr 29 10:07:15 2025 UTC elapsed time: 99760.203665 seconds (1d 3h 42m 40s)

---------------  T H R E A D  ---------------

Current thread (0x00007f5ba5761800):  JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=624036, stack(0x00007f5b784bf000,0x00007f5b785c0000)]


Current CompileTask:
C2:99760203 81632   !   4       oracle.net.resolver.AddrResolution::resolveAddrTree (232 bytes)

Stack: [0x00007f5b784bf000,0x00007f5b785c0000],  sp=0x00007f5b785bb5b0,  free space=1009k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xb127c5]  PhaseIdealLoop::identical_backtoback_ifs(Node*)+0x75
V  [libjvm.so+0xb12ad0]  PhaseIdealLoop::split_if_with_blocks_post(Node*, bool)+0x40
V  [libjvm.so+0xb13987]  PhaseIdealLoop::split_if_with_blocks(VectorSet&, Node_Stack&, bool)+0x187
V  [libjvm.so+0xb0cf41]  PhaseIdealLoop::build_and_optimize()+0xd61
V  [libjvm.so+0x678761]  Compile::Optimize()+0x311
V  [libjvm.so+0x67a165]  Compile::Compile(ciEnv*, C2Compiler*, ciMethod*, int, bool, bool, bool, bool, DirectiveSet*)+0xcb5
V  [libjvm.so+0x58be04]  C2Compiler::compile_method(ciEnv*, ciMethod*, int, DirectiveSet*)+0xd4
V  [libjvm.so+0x6844ba]  CompileBroker::invoke_compiler_on_method(CompileTask*)+0x3ca
V  [libjvm.so+0x685be8]  CompileBroker::compiler_thread_loop()+0x5a8
V  [libjvm.so+0xee28b0]  JavaThread::run()+0x280
V  [libjvm.so+0xedf27f]  Thread::call_run()+0x14f
V  [libjvm.so+0xc7b896]  thread_native_entry(Thread*)+0xe6


siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000020
```

### To Reproduce
Unknown, happens in COTs system at runtime. but happens frequently if we need to capture any other details

### Expected behavior
JVM Crash with core dump

### Platform information
    OS: [RHEL 8.10]
    Version [openjdk version "11.0.26" 2025-01-21 LTS OpenJDK Runtime Environment Corretto-11.0.26.4.1 (build 11.0.26+4-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.26.4.1 (build 11.0.26+4-LTS, mixed mode) ]

### Additional context
Crash Log Attached for reference

For VM crashes, please attach the error report file. By default the file name is `hs_err_pidpid.log`, where pid is the process ID of the process.

[replay_pid624012.log](https://github.com/user-attachments/files/19959717/replay_pid624012.log)
[hs_err_pid624012.log](https://github.com/user-attachments/files/19959716/hs_err_pid624012.log)

**Comment by zoomingrocket** [comment]
Close reference found for similar issue reported with Open JDK 17 - https://bugs.openjdk.org/browse/JDK-8353513

**Comment by olivergillespie** [comment]
Thanks, I've linked this issue in the OpenJDK ticket. So far it seems likely to be an OpenJDK issue, not specific to Corretto, so please follow the OpenJDK ticket for updates.

**Comment by zoomingrocket** [comment]
@olivergillespie - I see the parent bug marked as fixed in the JDK17 branch. Do we need to request an explicit backport to JDK 11?
https://bugs.openjdk.org/browse/JDK-8356031

**Comment by olivergillespie** [comment]
[JDK-8356031](https://bugs.openjdk.org/browse/JDK-8356031) is not fixed, it's closed as a duplicate of [JDK-8353513](https://bugs.openjdk.org/browse/JDK-8353513), which is open. There is no progress on a fix.

**Comment by zoomingrocket** [comment]
@olivergillespie - Thank you for the clarification, apologies for the false alert!
